popp-server:
  url: wss://popp-zeta-ingress:443/ws

connector:
  end-point-url: ${CONNECTOR_END_POINT_URL:https://127.0.0.1}
  log-ws: true
  secure:
    enable: ${CONNECTOR_SECURE_ENABLE:true}
    hostname-validation: ${CONNECTOR_SECURE_HOSTNAME_VALIDATION:false}
    keystore: ${CONNECTOR_SECURE_KEYSTORE:keystore.p12}
    keystore-password: ${CONNECTOR_SECURE_KEYSTORE_PASSWORD:changeit}
    trust-all: ${CONNECTOR_SECURE_TRUST_ALL:true}
    truststore: ${CONNECTOR_SECURE_TRUSTSTORE:truststore.p12}
    truststore-password: ${CONNECTOR_SECURE_TRUSTSTORE_PASSWORD:changeit}
  terminal-configuration:
    context:
      clientSystemId: ${CONTEXT_CLIENT_SYSTEM_ID:C1}
      workplaceId: ${CONTEXT_WORKPLACE_ID:W1}
      mandantId: ${CONTEXT_MANDANT_ID:M1}
    ct-id: ${CARD_TERMINAL_ID:ktId} # Identifikation des Kartenterminals

zeta:
  client:
    disableServerValidation: ${ZETA_CLIENT_DISABLE_SERVER_VALIDATION:true}
  authentication.smb:
    alias: ${ZETA_AUTHENTICATION_SMB_ALIAS:alias}
    keyfile: ${ZETA_AUTHENTICATION_SMB_KEYFILE:docker/zeta/smcb-private/smcb_private.p12}
    password: ${ZETA_AUTHENTICATION_SMB_PASSWORD:00}

card-reader:
  name: "REINER SCT"

virtual-card:
  image-file: "IMG_eGK_G21_TU_root6 1.xml"

popp-client:
  static-qr:
    tid: "1-20-ARV1661246300001992"
    wpid: ""
    size: 300

federation:
  keystore:
    location: "classpath:federation-keystore.jks"
    password: "gematik"
  entity-statement:
    url: "http://localhost:8443/.well-known/openid-federation"